language: c
sudo: false
dist: trusty
cache:
  ccache: true
compiler:
- gcc
- clang
install: 'true'
script:
- make
- ./mcrcon -h
- ./mcrcon -v
- make install PREFIX="${HOME}"
- make uninstall PREFIX="${HOME}"
